title: "Nehul Jain"
description: "Academic Profile"
theme: minima
markdown: kramdown
safe: false

plugins:
  - jekyll-scholar

author:
  name: "Nehul Jain"
  email: "nehul.jain26@gmail.com"

scholar:
  style: apa
  locale: en
  bibliography: publications.bib   # the file is in _bibliography/
  bibliography_template: bibentry
  sort_by: year
  order: descending
